export const PROJECTS = [
  {
    id: 1,
    title: "Fleet Management System",
    tag: "REACT.JS · REST API",
    year: "2023",
    desc: "Responsive fleet dashboards for managing vehicles, drivers, and status monitoring. Built reusable UI components and integrated REST APIs for dynamic data rendering.",
    detail: "Developed responsive fleet dashboards using React.js for managing vehicles, drivers, and status monitoring. Built reusable UI components and integrated REST APIs for dynamic data rendering. Implemented advanced filters, search, and reporting features for efficient fleet operations. Optimized performance and ensured cross-device compatibility using Bootstrap and modern CSS.",
    tech: ["React.js", "Bootstrap", "REST API", "Chrome DevTools"],
    accent: "#00FFB2",
    icon: "🚛",
  },
  {
    id: 2,
    title: "Trip Management System",
    tag: "REACT.JS · LEAFLET MAP",
    year: "2023",
    desc: "Trip creation and tracking modules with real-time UI updates. Interactive Leaflet map integration for live trip route and analytics dashboards.",
    detail: "Developed trip creation and tracking modules using React.js with real-time UI updates. Integrated REST APIs to display trip routes, status, and analytics dynamically. Designed interactive UI for showing trip track on the Leaflet map, monitoring, and reporting dashboards.",
    tech: ["React.js", "Leaflet", "REST API", "Tailwind CSS"],
    accent: "#FFB800",
    icon: "🗺️",
  },
  {
    id: 3,
    title: "IoT Solution Website",
    tag: "REACT.JS · TAILWIND CSS",
    year: "2024",
    desc: "Real-time monitoring dashboards with dynamic data visualization. Product showcase for GPS tracking solutions across fleet and mining industries.",
    detail: "Developed a responsive frontend using React.js and Tailwind CSS for real-time monitoring dashboards with dynamic data visualization. Built product showcase and UI components for GPS tracking solutions across industries including fleet management and mining.",
    tech: ["React.js", "Tailwind CSS", "Data Visualization"],
    accent: "#FF5C87",
    icon: "📡",
  },
  {
    id: 4,
    title: "Coal Mining Website",
    tag: "REACT.JS · TAILWIND CSS",
    year: "2024",
    desc: "Responsive, mobile-friendly website with modern UI design. Dynamic sections for mining services, product listings, and fleet infrastructure updates.",
    detail: "Developed a responsive, mobile-friendly website using React.js and Tailwind CSS with modern UI design, cross-browser compatibility, and performance optimization. Implemented dynamic sections for mining services, product listings, fleet details, and recent updates.",
    tech: ["React.js", "Tailwind CSS", "Responsive Design"],
    accent: "#7B61FF",
    icon: "⛏️",
  },
  {
    id: 5,
    title: "School Management System",
    tag: "HTML · CSS · JAVASCRIPT",
    year: "2022",
    desc: "Responsive frontend for managing academic data and user workflows. Intuitive UI for students and administrators with dynamic form validation.",
    detail: "Developed a responsive frontend using HTML5, CSS3, and JavaScript for managing academic data and user workflows. Designed intuitive UI for students and administrators with optimized UX and seamless navigation. Implemented dynamic features such as form validation, data handling, and interactive components.",
    tech: ["HTML5", "CSS3", "JavaScript", "UX Design"],
    accent: "#00C2FF",
    icon: "🏫",
  },
  {
    id: 6,
    title: "Beauty Parlor Website",
    tag: "HTML · BOOTSTRAP",
    year: "2022",
    desc: "Modern, responsive website that increased booking conversions by 25% through improved UI/UX design.",
    detail: "Designed and developed a modern, responsive website using HTML, CSS, JavaScript, and Bootstrap. Enhanced user engagement and increased booking conversions by 25% through improved UI/UX design and streamlined booking flows.",
    tech: ["HTML5", "CSS3", "Bootstrap", "JavaScript"],
    accent: "#FF8A00",
    icon: "💄",
  },
];

export const SKILLS = [
  { name: "React.js", level: 95 },
  { name: "JavaScript ES6+", level: 93 },
  { name: "HTML5 / CSS3", level: 97 },
  { name: "Tailwind CSS", level: 90 },
  { name: "REST API Integration", level: 88 },
  { name: "Performance Optimization", level: 85 },
  { name: "Bootstrap / Material UI", level: 87 },
  { name: "Git / GitHub", level: 85 },
];

export const EXPERIENCE = [
  {
    company: "Trans Global Geomatics Pvt Ltd",
    role: "Front-End Developer",
    period: "2022 – Present",
    location: "Hyderabad",
    points: [
      "Developed and maintained 15+ responsive web applications using React.js, HTML5, CSS3, and JavaScript ES6+.",
      "Built reusable and scalable UI components improving development efficiency and code maintainability.",
      "Integrated RESTful APIs using Fetch and Axios to handle dynamic data rendering and async operations.",
      "Optimized app performance with lazy loading and code splitting, reducing load time by 40%.",
      "Implemented responsive design using Bootstrap and Tailwind CSS for cross-device compatibility.",
      "Recognized for building reusable React components that reduced team development time by 30%.",
    ],
  },
  {
    company: "DDUGKY",
    role: "Web Developer Intern",
    period: "Feb 2022 – July 2022",
    location: "Vijayawada",
    points: [
      "Developed responsive web applications using HTML5, CSS3, JavaScript, and React.",
      "Implemented dynamic UI features including DOM manipulation, form validation, and reusable components.",
      "Assisted in API integration, debugging, and performance optimization using Chrome DevTools.",
    ],
  },
];
